### ISSUE TITLE
Examples produced by the CLI don't show correctly help options

### ISSUE THREAD

**Issue by jkakar** [interagent/heroics#28] opened 2014-04-28 21:21 UTC
The issue is related to resolving parameters in a janky way.  The work
in the client generator branch has the necessary pieces to fix this.

@markpundsack filed an issue about this:

oauth-client:delete doesn't seem to understand it's primary parameter.

```
$ bundle exec bin/heroku-api help oauth-client:delete
Usage: heroku-api oauth-client:delete

Description:
  Delete OAuth client.
```

Whereas something like app:delete shows:

```
$ bundle exec bin/heroku-api help app:delete
Usage: heroku-api app:delete <id|name>

Description:
  Delete an existing app.
```

**Comment by schneems** [comment] 2020-08-27 16:05
I tried reproducing this behavior and it looks like the `bin/heroku-api` script produces the correct output:

```
$ bundle exec bin/heroku-api help oauth-client:delete
Usage: heroku-api oauth-client:delete <id>

Description:
  Delete OAuth client.
```

Note the `<id>` present in this line:

```
Usage: heroku-api oauth-client:delete <id>
```

I believe we can close this issue.

**Closed by schneems** 2020-08-27 16:05 UTC
