### ISSUE TITLE
UTF-8 with bom fails generating a client

### ISSUE THREAD

**Issue by ailjushkin** [interagent/heroics#66] opened 2015-06-23 13:18 UTC
When my json schema is generated in 'utf-8 with bom' encoding, heroics-generate fails with error

**Comment by geemus** [comment] 2015-06-23 14:48
Could you share an example schema with this error (and perhaps the error itself)? Thanks!

**Comment by PositiveAlex** [comment] 2015-06-27 09:21
It is simple, you just save json with "utf8 with bom" encoding and try to
process it, this is caused by setting utf8 as encoding explicitly in your
code. Like encode('utf8'). I changed it to encode('bom|utf8') and it works.

17:48, Вт, 23.06.2015, Wesley Beary <notifications@github.com>:

**Comment by geemus** [comment] 2015-07-01 16:20
I see. Could you share a stacktrace? Hopefully we can ascertain a good approach (I've had a good deal of trouble tracing down encoding issues in Ruby historically).

**Comment by schneems** [comment] 2020-08-27 17:26
> It is simple, you just save json with "utf8 with bom" encoding and try to

I don't know what this means. Can you provide an example app or reproduction (https://www.codetriage.com/example_app)? 

I'm going to close this issue until we can get a reproduction. Feel free to reply back or open a new issue once you've got a reproduction then we can investigate.

**Closed by schneems** 2020-08-27 17:26 UTC
